"""增加Flask-PageDown 即博客文章属性

Revision ID: 17e9a3909e26
Revises: f6f8fd553c4c
Create Date: 2016-03-04 21:13:00.942764

"""

# revision identifiers, used by Alembic.
revision = '17e9a3909e26'
down_revision = 'f6f8fd553c4c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
