"""initial migration

Revision ID: 4938b68be6ee
Revises: 6bd2cc30eeca
Create Date: 2016-02-28 15:30:49.446696

"""

# revision identifiers, used by Alembic.
revision = '4938b68be6ee'
down_revision = '6bd2cc30eeca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
