"""comment

Revision ID: c70c2dd58ebb
Revises: efb0f3d8e4d2
Create Date: 2016-03-14 21:39:53.872842

"""

# revision identifiers, used by Alembic.
revision = 'c70c2dd58ebb'
down_revision = 'efb0f3d8e4d2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'body_html')
    ### end Alembic commands ###
