"""增加avatar_hash属性 头像散列值

Revision ID: fa58b20932f4
Revises: 975b18abd7d5
Create Date: 2016-03-02 23:30:12.714711

"""

# revision identifiers, used by Alembic.
revision = 'fa58b20932f4'
down_revision = '975b18abd7d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
